# Generated by Django 4.1.6 on 2023-02-22 15:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('issue_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_activity_date', models.DateTimeField(blank=True, null=True)),
                ('last_usage_date', models.DateTimeField(blank=True, null=True)),
                ('purchases_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('not_activated', 'Not Activated'), ('activated', 'Activated'), ('expired', 'Expired')], default='not_activated', max_length=15)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CardTrash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('issue_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_activity_date', models.DateTimeField(blank=True, null=True)),
                ('last_usage_date', models.DateTimeField(blank=True, null=True)),
                ('purchases_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('not_activated', 'Not Activated'), ('activated', 'Activated'), ('expired', 'Expired')], default='not_activated', max_length=15)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Card Trash',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('order_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bonus.card')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bonus.order')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_orders',
            field=models.ManyToManyField(blank=True, related_name='cards', to='bonus.order'),
        ),
    ]
